<?php

namespace HeadlessCart\Contact;

use WP_REST_Request;
use WP_REST_Response;
use WP_Error;

if (!defined('ABSPATH')) exit;

/**
 * Handles the contact form submission:
 *
 *   POST /headlesscart/v1/contact/send
 *
 * Features:
 * - Fully public endpoint (no auth)
 * - Sanitization + basic validation
 * - Sends HTML email to site admin
 * - Ready for headless frontends (Next.js, React, Vue)
 */
class ContactController
{
    /**
     * Main handler for form submission.
     *
     * @param WP_REST_Request $req
     * @return WP_REST_Response|WP_Error
     */
    public static function handle(WP_REST_Request $req)
    {
        // -----------------------------
        // Extract & sanitize input
        // -----------------------------
        $name    = sanitize_text_field($req->get_param('name'));
        $company = sanitize_text_field($req->get_param('company'));
        $email   = sanitize_email($req->get_param('email'));
        $phone   = sanitize_text_field($req->get_param('phone'));
        $service = sanitize_text_field($req->get_param('service'));
        $message = sanitize_textarea_field($req->get_param('message'));
        $privacy = $req->get_param('privacy');

        // -----------------------------
        // Basic validation
        // -----------------------------
        if (!$name || !$email || !$message) {
            return new WP_REST_Response([
                'success' => false,
                'error'   => 'Missing required fields'
            ], 400);
        }

        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return new WP_REST_Response([
                'success' => false,
                'error'   => 'Invalid email format'
            ], 400);
        }

        if (!$privacy) {
            return new WP_REST_Response([
                'success' => false,
                'error'   => 'Privacy consent required'
            ], 400);
        }

        // -----------------------------
        // Build email
        // -----------------------------
        $adminEmail = get_option('admin_email');
        $subject    = "New contact form submission";

        ob_start();
        ?>
        <html>
        <body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background:#f2f4f7;">

        <div style="
            max-width:600px;
            margin:30px auto;
            background:#ffffff;
            border-radius:10px;
            overflow:hidden;
            box-shadow:0 4px 12px rgba(0,0,0,0.1);
        ">

            <!-- Header -->
            <div style="background:linear-gradient(90deg,#17C8F1,#0077D4);padding:20px;color:#fff;text-align:center;">
                <h2 style="margin:0;font-size:22px;font-weight:600;">New Contact Form Message</h2>
            </div>

            <!-- Content -->
            <div style="padding:25px 30px;color:#333;">
                <h3 style="margin-top:0;font-size:18px;color:#0077D4;">Details</h3>

                <p><strong>Name:</strong> <?php echo esc_html($name); ?></p>
                <?php if ($company) : ?>
                    <p><strong>Company:</strong> <?php echo esc_html($company); ?></p>
                <?php endif; ?>

                <p><strong>Email:</strong> <?php echo esc_html($email); ?></p>

                <?php if ($phone) : ?>
                    <p><strong>Phone:</strong> <?php echo esc_html($phone); ?></p>
                <?php endif; ?>

                <?php if ($service) : ?>
                    <p><strong>Requested service:</strong> <?php echo esc_html($service); ?></p>
                <?php endif; ?>

                <div style="
                    margin-top:20px;
                    padding:15px;
                    background:#f7fbff;
                    border-left:4px solid #0077D4;
                    border-radius:5px;
                ">
                    <p style="margin:0;font-size:15px;line-height:1.5;">
                        <?php echo nl2br(esc_html($message)); ?>
                    </p>
                </div>
            </div>

            <!-- Footer -->
            <div style="background:#f0f0f0;padding:15px 20px;text-align:center;font-size:12px;color:#555;">
                This email was automatically generated by <strong>HeadlessCart</strong>.
            </div>

        </div>

        </body>
        </html>
        <?php
        $html = ob_get_clean();

        $headers = [
            'Content-Type: text/html; charset=UTF-8',
            'Reply-To: ' . $email,
        ];

        // -----------------------------
        // Send email
        // -----------------------------
        $sent = wp_mail($adminEmail, $subject, $html, $headers);

        if (!$sent) {
            return new WP_REST_Response([
                'success' => false,
                'error'   => 'Mail sending failed',
            ], 500);
        }

        return new WP_REST_Response([
            'success' => true,
            'message' => 'Message sent successfully'
        ], 200);
    }
}
